language: python
python:
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
jobs:
  include:
    - stage: "Lexer"
      name: "Lexer" 
      script: 
        - cd src
        - make clean
        - make
        - make test TAG=lexer
    - stage: "Parser"
      name: "Parser" 
      script: 
        - cd src
        - make clean
        - make
        - make test TAG=parser