# lextab.py. This file automatically created by PLY (version 3.11). Don't edit!
_tabversion   = '3.10'
_lextokens    = set(('ARROW', 'ASSIGN', 'AT', 'BOOL_TYPE', 'CASE', 'CLASS', 'COLON', 'COMMA', 'DIVIDE', 'DOT', 'ELSE', 'EQ', 'ESAC', 'FALSE', 'FALSELPAREN', 'FI', 'ID', 'IF', 'IN', 'INHERITS', 'INTEGER', 'INT_COMP', 'INT_TYPE', 'IO_TYPE', 'ISVOID', 'LBRACE', 'LET', 'LOOP', 'LT', 'LTEQ', 'LexicographicError', 'MAIN_TYPE', 'MINUS', 'MULTIPLY', 'NEW', 'NOT', 'OBJECT_TYPE', 'OF', 'PLUS', 'POOL', 'RBRACE', 'RPAREN', 'SELF', 'SELF_TYPE', 'SEMICOLON', 'STRING', 'STRING_TYPE', 'THEN', 'TRUE', 'TYPE', 'WHILE'))
_lexreflags   = 64
_lexliterals  = ''
_lexstateinfo = {'INITIAL': 'inclusive', 'STRING': 'exclusive', 'COMMENT': 'exclusive'}
_lexstatere   = {'INITIAL': [('(?P<t_INTEGER>\\d+)|(?P<t_TYPE>[A-Z][a-zA-Z_0-9]*)|(?P<t_ID>[a-z][a-zA-Z_0-9]*)|(?P<t_newline>\\n+)|(?P<t_start_string_state>\\")|(?P<t_start_comment_state>\\(\\*)|(?P<t_ignore_SINGLE_LINE_COMMENT>\\-\\-[^\\n]*)|(?P<t_ARROW>\\=\\>)|(?P<t_ASSIGN>\\<\\-)|(?P<t_LTEQ>\\<\\=)|(?P<t_AT>\\@)|(?P<t_COLON>\\:)|(?P<t_COMMA>\\,)|(?P<t_DIVIDE>\\/)|(?P<t_DOT>\\.)|(?P<t_EQ>\\=)|(?P<t_LBRACE>\\{)|(?P<t_LPAREN>\\()|(?P<t_LT>\\<)|(?P<t_MINUS>\\-)|(?P<t_MULTIPLY>\\*)|(?P<t_PLUS>\\+)|(?P<t_RBRACE>\\})|(?P<t_RPAREN>\\))|(?P<t_SEMICOLON>\\;)|(?P<t_INT_COMP>~)', [None, ('t_INTEGER', 'INTEGER'), ('t_TYPE', 'TYPE'), ('t_ID', 'ID'), ('t_newline', 'newline'), ('t_start_string_state', 'start_string_state'), ('t_start_comment_state', 'start_comment_state'), (None, None), (None, 'ARROW'), (None, 'ASSIGN'), (None, 'LTEQ'), (None, 'AT'), (None, 'COLON'), (None, 'COMMA'), (None, 'DIVIDE'), (None, 'DOT'), (None, 'EQ'), (None, 'LBRACE'), (None, 'LPAREN'), (None, 'LT'), (None, 'MINUS'), (None, 'MULTIPLY'), (None, 'PLUS'), (None, 'RBRACE'), (None, 'RPAREN'), (None, 'SEMICOLON'), (None, 'INT_COMP')])], 'STRING': [('(?P<t_STRING_newline>\\n)|(?P<t_STRING_null>\\0)|(?P<t_STRING_end>\\")|(?P<t_STRING_anything>[^\\n])', [None, ('t_STRING_newline', 'newline'), ('t_STRING_null', 'null'), ('t_STRING_end', 'end'), ('t_STRING_anything', 'anything')])], 'COMMENT': [('(?P<t_COMMENT_newline>\\n+)|(?P<t_COMMENT_begin_another_comment>\\(\\*)|(?P<t_COMMENT_end>\\*\\))', [None, ('t_COMMENT_newline', 'newline'), ('t_COMMENT_begin_another_comment', 'begin_another_comment'), ('t_COMMENT_end', 'end')])]}
_lexstateignore = {'COMMENT': '', 'STRING': '', 'INITIAL': ' \t\r\x0c'}
_lexstateerrorf = {'COMMENT': 't_COMMENT_error', 'STRING': 't_STRING_error', 'INITIAL': 't_error'}
_lexstateeoff = {'COMMENT': 't_COMMENT_eof', 'STRING': 't_STRING_eof'}
