name: Tests

on: [push, pull_request]

jobs:
  lexer:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run tests
        run: |
          cd src
          make clean
          make
          make test TAG=lexer

  parser:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run tests
        run: |
          cd src
          make clean
          make
          make test TAG=parser

  semantic:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run tests
        run: |
          cd src
          make clean
          make
          make test TAG=semantic

  codegen:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Install spim
        run: sudo apt-get install spim

      - name: Run tests
        run: |
          cd src
          make clean
          make
          make test TAG=codegen
